.github: workflows: rust-clippy: build before running rust-clippy
This is needed to generate required files, such as:
  - config.rs from config.rs.in

```
error: could not compile `epic_asset_manager` (bin "epic_asset_manager") due to 1 previous error; 10 warnings emitted
error: file not found for module `config`
  ┌─ src/main.rs:3:1
  │
3 │ mod config;
  │ ^^^^^^^^^^^
  │
  = to create the module `config`, create file "src/config.rs" or "src/config/mod.rs"
    if there is a `mod config` elsewhere in the crate already, import it with `use crate::...` instead
```

Signed-off-by: Alexander Martinz <alex@amartinz.at>